### ISSUE TITLE
可以手动触发通知 定时不起作用，登陆了一次账号后续不能换账号不能换群也不显示已经登陆了账号但可以手动触发通知

### ISSUE THREAD

**Issue by bzhd** [PBK-B/mirai-class-notice#11]
![QQ图片20210901154843](https://user-images.githubusercontent.com/82311574/131633289-1b8e96d9-75c1-4fe2-8688-c7a841475913.png)
![QQ图片20210901154849](https://user-images.githubusercontent.com/82311574/131633294-701674e5-8347-463d-b75a-ac3488c8b7dc.png)
![QQ图片20210901155627](https://user-images.githubusercontent.com/82311574/131634240-6cc40763-e1fb-465e-b107-7ebf968394be.png)

本来想研究下源码，结果半天没有搞好go语言环境，vscode装不上go插件，翻墙也装不上

**Comment by PBK-B** [comment]
@bzhd 可以切换账号呀，换群的话在登陆之后加入的群可以通过重新登陆账号刷新群列表

**Comment by PBK-B** [comment]
定时设置不起作用问题已经修复发布最新的 class-notice_linux.tar.gz 版本啦

**Comment by PBK-B** [comment]
@bzhd QQ 账号登陆态消失的问题已经修复了 https://github.com/PBK-B/mirai-class-notice/commit/af0ff596a48d5d521ec0c0b2ab6c1d3a8def462e
下载最新版本 class-notice_linux.tar.gz 就好了

**Comment by sbcxk** [comment]
大佬可以更新一下Releases里面的吗，这里面还是8天前的哈
