### ISSUE TITLE
QQ无法登陆问题能否解决

### ISSUE THREAD

**Issue by azi666** [PBK-B/mirai-class-notice#14]
![image](https://user-images.githubusercontent.com/57692681/134553452-b34ccb9e-d3ef-4376-b132-f1b3e9bf1722.png)

**Comment by PBK-B** [comment]
https://github.com/PBK-B/mirai-class-notice/issues/8#issuecomment-906104558

**Comment by PBK-B** [comment]
https://github.com/PBK-B/mirai-class-notice/issues/4#issuecomment-905483607
