### ISSUE TITLE
无法正确启动机器人

### ISSUE THREAD

**Issue by FW27623** [PBK-B/mirai-class-notice#3]
输入./class_notice运行时，机器人被启动，随后就被关闭，报错提示bind: cannot assign requested address，使用网上的方法设置net.ipv4.tcp_tw_reuse = 1这个方法无效。

**Comment by FW27623** [comment]
在app.conf里已正确修改配置，数据库连接正常，表格已创建完成，但机器人无法启动

**Comment by PBK-B** [comment]
@FW27623 把 app.conf 文件中的 httpport 字段改其他值试试？
```
appname = class_notice
httpaddr = 0.0.0.0
httpport = 9961
runmode = prod
dbhost = 127.0.0.1:3306
dbdriver = mysql
dbusername = root
dbpassword = mysqlpassword
dbdatabase = test_class_notice
```

**Comment by 778147282** [comment]
> 
> 
> @FW27623 把 app.conf 文件中的 httpport 字段改其他值试试？
> 
> ```
> appname = class_notice
> httpaddr = 0.0.0.0
> httpport = 9961
> runmode = prod
> dbhost = 127.0.0.1:3306
> dbdriver = mysql
> dbusername = root
> dbpassword = mysqlpassword
> dbdatabase = test_class_notice
> ```
这些能给个注释吗 对小白不太友好

**Comment by PBK-B** [comment]
> > @FW27623 把 app.conf 文件中的 httpport 字段改其他值试试？
> > ```
> > appname = class_notice
> > httpaddr = 0.0.0.0
> > httpport = 9961
> > runmode = prod
> > dbhost = 127.0.0.1:3306
> > dbdriver = mysql
> > dbusername = root
> > dbpassword = mysqlpassword
> > dbdatabase = test_class_notice
> > ```
> 
> 这些能给个注释吗 对小白不太友好

```
appname = class_notice               // 这是程序名称，不用管
httpaddr = 0.0.0.0                          // 这是 IP 地址 0.0.0.0 表示本机
httpport = 8089                             // 这是端口号，登陆控制台的时候需要加上这个端口号
runmode = prod                             // 这个不用管表示线上环境的
dbhost = 127.0.0.1:3306                // 这是 mysql 数据库地址
dbdriver = mysql                            // 表示使用 mysql 数据库
dbusername = root                        // 登陆数据库的用户名
dbpassword = mysqlpassword     // 数据库密码
dbdatabase = test_class_notice  // 数据库表名（一般不用改）
```

**Comment by 778147282** [comment]
> 
> 
> > > @FW27623 把 app.conf 文件中的 httpport 字段改其他值试试？
> > > ```
> > > appname = class_notice
> > > httpaddr = 0.0.0.0
> > > httpport = 9961
> > > runmode = prod
> > > dbhost = 127.0.0.1:3306
> > > dbdriver = mysql
> > > dbusername = root
> > > dbpassword = mysqlpassword
> > > dbdatabase = test_class_notice
> > > ```
> > 
> > 
> > 这些能给个注释吗 对小白不太友好
> 
> ```
> appname = class_notice               // 这是程序名称，不用管
> httpaddr = 0.0.0.0                          // 这是 IP 地址 0.0.0.0 表示本机
> httpport = 8089                             // 这是端口号，登陆控制台的时候需要加上这个端口号
> runmode = prod                             // 这个不用管表示线上环境的
> dbhost = 127.0.0.1:3306                // 这是 mysql 数据库地址
> dbdriver = mysql                            // 表示使用 mysql 数据库
> dbusername = root                        // 登陆数据库的用户名
> dbpassword = mysqlpassword     // 数据库密码
> dbdatabase = test_class_notice  // 数据库表名（一般不用改）
> ```

感谢大佬！大佬硬邦邦！

**Comment by FW27623** [comment]
我试过了换端口，然后在防火墙把端口开放，但是都无法奏效，还是显示以上错误

**Comment by FW27623** [comment]
> @FW27623 把 app.conf 文件中的 httpport 字段改其他值试试？
> 
> ```
> appname = class_notice
> httpaddr = 0.0.0.0
> httpport = 9961
> runmode = prod
> dbhost = 127.0.0.1:3306
> dbdriver = mysql
> dbusername = root
> dbpassword = mysqlpassword
> dbdatabase = test_class_notice
> ```

我试过更改端口，然而还是不起作用，在启动的时候机器人会打开然后立马关闭报错，端口也没有占用，防火墙也打开过对应端口

**Comment by PBK-B** [comment]
> > @FW27623 把 app.conf 文件中的 httpport 字段改其他值试试？
> > ```
> > appname = class_notice
> > httpaddr = 0.0.0.0
> > httpport = 9961
> > runmode = prod
> > dbhost = 127.0.0.1:3306
> > dbdriver = mysql
> > dbusername = root
> > dbpassword = mysqlpassword
> > dbdatabase = test_class_notice
> > ```
> 
> 我试过更改端口，然而还是不起作用，在启动的时候机器人会打开然后立马关闭报错，端口也没有占用，防火墙也打开过对应端口

贴一下输出 log

**Comment by FW27623** [comment]
![image](https://user-images.githubusercontent.com/59783568/130781263-ef9fc62a-c08c-4a01-93f6-cc99d81d84ff.png)
![image](https://user-images.githubusercontent.com/59783568/130781469-52698f5d-a3a3-430f-bc0f-ed54150b9c4c.png)

**Comment by FW27623** [comment]
大佬，请问下这个是那个地方出错了吗？

**Comment by PBK-B** [comment]
> 大佬，请问下这个是那个地方出错了吗？

@FW27623 你这没问题呀，访问不了吗？

**Comment by FW27623** [comment]
> > 大佬，请问下这个是那个地方出错了吗？
> 
> @FW27623 你这没问题呀，访问不了吗？

访问不了，bot停止了

**Comment by FW27623** [comment]
![image](https://user-images.githubusercontent.com/59783568/130793227-44deeb62-ab78-484f-ae16-985075b2da97.png)
端口是放开的，输入ip:8089显示http error 502
![image](https://user-images.githubusercontent.com/59783568/130793438-d3207519-c14a-4c88-8686-68a2ee6af98d.png)

**Comment by PBK-B** [comment]
> ![image](https://user-images.githubusercontent.com/59783568/130793227-44deeb62-ab78-484f-ae16-985075b2da97.png)
> 端口是放开的，输入ip:8089显示http error 502
> ![image](https://user-images.githubusercontent.com/59783568/130793438-d3207519-c14a-4c88-8686-68a2ee6af98d.png)

连后台都访问不了是吧？要不你把 nohup.out 文件发我邮箱 bin@pbk6.cn 或者加我 QQ 2404316326 我看看输出文件

**Comment by FW27623** [comment]
> > ![image](https://user-images.githubusercontent.com/59783568/130793227-44deeb62-ab78-484f-ae16-985075b2da97.png)
> > 端口是放开的，输入ip:8089显示http error 502
> > ![image](https://user-images.githubusercontent.com/59783568/130793438-d3207519-c14a-4c88-8686-68a2ee6af98d.png)
> 
> 连后台都访问不了是吧？要不你把 nohup.out 文件发我邮箱 [bin@pbk6.cn](mailto:bin@pbk6.cn) 或者加我 QQ 2404316326 我看看输出文件

对的，
好的我加你QQ了
