### ISSUE TITLE
设置qq点击登入后系统设置界面白屏，重启后仍然一样

### ISSUE THREAD

**Issue by ayyz666** [PBK-B/mirai-class-notice#4]
无报错，其他页面正常，但就进不去系统设置了

**Comment by FW27623** [comment]
我都启动不起来，也不知道怎么弄

**Comment by ayyz666** [comment]
> 我都启动不起来，也不知道怎么弄

我这边好像也是bot问题，不过能启动起来

**Comment by ayyz666** [comment]
这是 log

{"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:30:06+08:00"}
{"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:30:19+08:00"}
{"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:31:44+08:00"}
{"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:32:52+08:00"}
{"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:37:31+08:00"}
{"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:38:54+08:00"}
{"bot":"internal","level":"info","msg":"initializing modules ...","time":"2021-08-25T19:44:14+08:00"}
{"bot":"internal","level":"info","msg":"all modules initialized","time":"2021-08-25T19:44:14+08:00"}
{"bot":"internal","level":"info","msg":"registering modules serve functions ...","time":"2021-08-25T19:44:14+08:00"}
{"bot":"internal","level":"info","msg":"all modules serve functions registered","time":"2021-08-25T19:44:14+08:00"}
{"bot":"internal","level":"info","msg":"starting modules tasks ...","time":"2021-08-25T19:44:14+08:00"}
{"bot":"internal","level":"info","msg":"tasks running","time":"2021-08-25T19:44:14+08:00"}
{"bot":"internal","level":"info","msg":"initializing modules ...","time":"2021-08-25T19:44:24+08:00"}
{"bot":"internal","level":"info","msg":"all modules initialized","time":"2021-08-25T19:44:24+08:00"}
{"bot":"internal","level":"info","msg":"registering modules serve functions ...","time":"2021-08-25T19:44:24+08:00"}
{"bot":"internal","level":"info","msg":"all modules serve functions registered","time":"2021-08-25T19:44:24+08:00"}
{"bot":"internal","level":"info","msg":"starting modules tasks ...","time":"2021-08-25T19:44:24+08:00"}
{"bot":"internal","level":"info","msg":"tasks running","time":"2021-08-25T19:44:24+08:00"}
{"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:46:41+08:00"}
{"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:57:43+08:00"}
{"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:57:48+08:00"}

**Comment by FW27623** [comment]
> > 我都启动不起来，也不知道怎么弄
> 
> 我这边好像也是bot问题，不过能启动起来

我是直接warning，然后直接停了，界面都打不开

**Comment by PBK-B** [comment]
> 这是 log
> 
> {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:30:06+08:00"}
> {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:30:19+08:00"}
> {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:31:44+08:00"}
> {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:32:52+08:00"}
> {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:37:31+08:00"}
> {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:38:54+08:00"}
> {"bot":"internal","level":"info","msg":"initializing modules ...","time":"2021-08-25T19:44:14+08:00"}
> {"bot":"internal","level":"info","msg":"all modules initialized","time":"2021-08-25T19:44:14+08:00"}
> {"bot":"internal","level":"info","msg":"registering modules serve functions ...","time":"2021-08-25T19:44:14+08:00"}
> {"bot":"internal","level":"info","msg":"all modules serve functions registered","time":"2021-08-25T19:44:14+08:00"}
> {"bot":"internal","level":"info","msg":"starting modules tasks ...","time":"2021-08-25T19:44:14+08:00"}
> {"bot":"internal","level":"info","msg":"tasks running","time":"2021-08-25T19:44:14+08:00"}
> {"bot":"internal","level":"info","msg":"initializing modules ...","time":"2021-08-25T19:44:24+08:00"}
> {"bot":"internal","level":"info","msg":"all modules initialized","time":"2021-08-25T19:44:24+08:00"}
> {"bot":"internal","level":"info","msg":"registering modules serve functions ...","time":"2021-08-25T19:44:24+08:00"}
> {"bot":"internal","level":"info","msg":"all modules serve functions registered","time":"2021-08-25T19:44:24+08:00"}
> {"bot":"internal","level":"info","msg":"starting modules tasks ...","time":"2021-08-25T19:44:24+08:00"}
> {"bot":"internal","level":"info","msg":"tasks running","time":"2021-08-25T19:44:24+08:00"}
> {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:46:41+08:00"}
> {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:57:43+08:00"}
> {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:57:48+08:00"}

@ayyz666 新账号登陆是会有点小问题的，我抽个时间重写一下这块的代码

**Comment by ayyz666** [comment]
> > 这是 log
> > {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:30:06+08:00"}
> > {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:30:19+08:00"}
> > {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:31:44+08:00"}
> > {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:32:52+08:00"}
> > {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:37:31+08:00"}
> > {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:38:54+08:00"}
> > {"bot":"internal","level":"info","msg":"initializing modules ...","time":"2021-08-25T19:44:14+08:00"}
> > {"bot":"internal","level":"info","msg":"all modules initialized","time":"2021-08-25T19:44:14+08:00"}
> > {"bot":"internal","level":"info","msg":"registering modules serve functions ...","time":"2021-08-25T19:44:14+08:00"}
> > {"bot":"internal","level":"info","msg":"all modules serve functions registered","time":"2021-08-25T19:44:14+08:00"}
> > {"bot":"internal","level":"info","msg":"starting modules tasks ...","time":"2021-08-25T19:44:14+08:00"}
> > {"bot":"internal","level":"info","msg":"tasks running","time":"2021-08-25T19:44:14+08:00"}
> > {"bot":"internal","level":"info","msg":"initializing modules ...","time":"2021-08-25T19:44:24+08:00"}
> > {"bot":"internal","level":"info","msg":"all modules initialized","time":"2021-08-25T19:44:24+08:00"}
> > {"bot":"internal","level":"info","msg":"registering modules serve functions ...","time":"2021-08-25T19:44:24+08:00"}
> > {"bot":"internal","level":"info","msg":"all modules serve functions registered","time":"2021-08-25T19:44:24+08:00"}
> > {"bot":"internal","level":"info","msg":"starting modules tasks ...","time":"2021-08-25T19:44:24+08:00"}
> > {"bot":"internal","level":"info","msg":"tasks running","time":"2021-08-25T19:44:24+08:00"}
> > {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:46:41+08:00"}
> > {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:57:43+08:00"}
> > {"bot":"internal","level":"info","msg":"stopped","time":"2021-08-25T19:57:48+08:00"}
> 
> @ayyz666 新账号登陆是会有点小问题的，我抽个时间重写一下这块的代码

OK  膜拜一下

**Comment by PBK-B** [comment]
@ayyz666 等下我给你一个解决方案

**Comment by PBK-B** [comment]
@ayyz666 目前腾讯对QQ号第一次登陆陌生设备有做调整，所以需要弄一个设备的 json 配置文件。
1，先下载这个 APK：<https://github.com/PBK-B/mirai-class-notice/releases/download/v0.1-Beta/MiraiAndroid_3.2.1.apk>
2，利用 MiraiAndroid 登陆 QQ 账号后导出 device.json
![1100221](https://user-images.githubusercontent.com/39079814/130795493-5d2035c6-910c-4608-9d34-2ba6cd9bd8b5.png)
3，替换服务器中的 device.json 文件

你试试这个方案。

**Comment by ayyz666** [comment]
> @ayyz666 目前腾讯对QQ号第一次登陆陌生设备有做调整，所以需要弄一个设备的 json 配置文件。
> 1，先下载这个 APK：https://github.com/PBK-B/mirai-class-notice/releases/download/v0.1-Beta/MiraiAndroid_3.2.1.apk
> 2，利用 MiraiAndroid 登陆 QQ 账号后导出 device.json
> ![1100221](https://user-images.githubusercontent.com/39079814/130795493-5d2035c6-910c-4608-9d34-2ba6cd9bd8b5.png)
> 3，替换服务器中的 device.json 文件
> 
> 你试试这个方案。

PANI[0002] device.json error                             bot=internal error="failed to unmarshal json message: client.DeviceInfoFile.Display: ReadString: expects \" or n, but found [, error found in #10 byte of ...|isplay\": [\n        7|..., bigger context ...|{\n    \"display\": [\n        77,\n        73,\n        82,\n        65,\n |..."
panic: (*logrus.Entry) 0xc00016a070

goroutine 16 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc00016a000, 0x0, 0xc0005b87a0, 0x11)
        /Users/bin/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x2e5
github.com/sirupsen/logrus.(*Entry).Log(0xc00016a000, 0xc000000000, 0xc0000a5c90, 0x1, 0x1)
        /Users/bin/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x86
github.com/sirupsen/logrus.(*Entry).Panic(...)
        /Users/bin/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:323
github.com/Logiase/MiraiGo-Template/bot.InitBot(0xc3aee28e, 0xc0003e4540, 0xa)
        /Users/bin/go/pkg/mod/github.com/!logiase/!mirai!go-!template@v0.0.0-20210309153626-69cfb14d2cd1/bot/bot.go:58 +0x24b
class_notice/helper.InitBot(0xc3aee28e, 0xc0003e4540, 0xa, 0xc00003ada0, 0xc0003c0b60)
        /Volumes/tzmaxData/data/web/class_notice/helper/bot.go:34 +0x5d
created by class_notice/controllers/apis.(*BotController).ApiBotLogin
        /Volumes/tzmaxData/data/web/class_notice/controllers/apis/bot.go:52 +0x393
现在这样登入就开始报错了

**Comment by PBK-B** [comment]
> > @ayyz666 目前腾讯对QQ号第一次登陆陌生设备有做调整，所以需要弄一个设备的 json 配置文件。
> > 1，先下载这个 APK：https://github.com/PBK-B/mirai-class-notice/releases/download/v0.1-Beta/MiraiAndroid_3.2.1.apk
> > 2，利用 MiraiAndroid 登陆 QQ 账号后导出 device.json
> > ![1100221](https://user-images.githubusercontent.com/39079814/130795493-5d2035c6-910c-4608-9d34-2ba6cd9bd8b5.png)
> > 3，替换服务器中的 device.json 文件
> > 你试试这个方案。
> 
> PANI[0002] device.json error bot=internal error="failed to unmarshal json message: client.DeviceInfoFile.Display: ReadString: expects " or n, but found [, error found in #10 byte of ...|isplay": [\n 7|..., bigger context ...|{\n "display": [\n 77,\n 73,\n 82,\n 65,\n |..."
> panic: (*logrus.Entry) 0xc00016a070
> 
> goroutine 16 [running]:
> github.com/sirupsen/logrus.(*Entry).log(0xc00016a000, 0x0, 0xc0005b87a0, 0x11)
> /Users/bin/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x2e5
> github.com/sirupsen/logrus.(*Entry).Log(0xc00016a000, 0xc000000000, 0xc0000a5c90, 0x1, 0x1)
> /Users/bin/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x86
> github.com/sirupsen/logrus.(*Entry).Panic(...)
> /Users/bin/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:323
> github.com/Logiase/MiraiGo-Template/bot.InitBot(0xc3aee28e, 0xc0003e4540, 0xa)
> /Users/bin/go/pkg/mod/github.com/!logiase/!mirai!go-!template@v0.0.0-20210309153626-69cfb14d2cd1/bot/bot.go:58 +0x24b
> class_notice/helper.InitBot(0xc3aee28e, 0xc0003e4540, 0xa, 0xc00003ada0, 0xc0003c0b60)
> /Volumes/tzmaxData/data/web/class_notice/helper/bot.go:34 +0x5d
> created by class_notice/controllers/apis.(*BotController).ApiBotLogin
> /Volumes/tzmaxData/data/web/class_notice/controllers/apis/bot.go:52 +0x393
> 现在这样登入就开始报错了

刚刚写工具去啦，先用这个工具转换一下：<http://mirai-devicejs-analyze.zmkj6.top/>
将转换后的内容替换 device.json 中的内容。

**Comment by ayyz666** [comment]
> > > @ayyz666 目前腾讯对QQ号第一次登陆陌生设备有做调整，所以需要弄一个设备的 json 配置文件。
> > > 1，先下载这个 APK：https://github.com/PBK-B/mirai-class-notice/releases/download/v0.1-Beta/MiraiAndroid_3.2.1.apk
> > > 2，利用 MiraiAndroid 登陆 QQ 账号后导出 device.json
> > > ![1100221](https://user-images.githubusercontent.com/39079814/130795493-5d2035c6-910c-4608-9d34-2ba6cd9bd8b5.png)
> > > 3，替换服务器中的 device.json 文件
> > > 你试试这个方案。
> > 
> > 
> > PANI[0002] device.json error bot=internal error="failed to unmarshal json message: client.DeviceInfoFile.Display: ReadString: expects " or n, but found [, error found in #10 byte of ...|isplay": [\n 7|..., bigger context ...|{\n "display": [\n 77,\n 73,\n 82,\n 65,\n |..."
> > panic: (*logrus.Entry) 0xc00016a070
> > goroutine 16 [running]:
> > github.com/sirupsen/logrus.(*Entry).log(0xc00016a000, 0x0, 0xc0005b87a0, 0x11)
> > /Users/bin/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x2e5
> > github.com/sirupsen/logrus.(*Entry).Log(0xc00016a000, 0xc000000000, 0xc0000a5c90, 0x1, 0x1)
> > /Users/bin/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x86
> > github.com/sirupsen/logrus.(*Entry).Panic(...)
> > /Users/bin/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:323
> > github.com/Logiase/MiraiGo-Template/bot.InitBot(0xc3aee28e, 0xc0003e4540, 0xa)
> > /Users/bin/go/pkg/mod/github.com/!logiase/!mirai!go-!template@v0.0.0-20210309153626-69cfb14d2cd1/bot/bot.go:58 +0x24b
> > class_notice/helper.InitBot(0xc3aee28e, 0xc0003e4540, 0xa, 0xc00003ada0, 0xc0003c0b60)
> > /Volumes/tzmaxData/data/web/class_notice/helper/bot.go:34 +0x5d
> > created by class_notice/controllers/apis.(*BotController).ApiBotLogin
> > /Volumes/tzmaxData/data/web/class_notice/controllers/apis/bot.go:52 +0x393
> > 现在这样登入就开始报错了
> 
> 刚刚写工具去啦，先用这个工具转换一下：http://mirai-devicejs-analyze.zmkj6.top/
> 将转换后的内容替换 device.json 中的内容。

转换后点击登入后刚开始显示登入成功然后还是白屏
INFO[0040] initializing modules ...                      bot=internal
INFO[0040] all modules initialized                       bot=internal
INFO[0040] registering modules serve functions ...       bot=internal
INFO[0040] all modules serve functions registered        bot=internal
INFO[0040] starting modules tasks ...                    bot=internal
INFO[0040] tasks running                                 bot=internal
INFO[0044] initializing modules ...                      bot=internal
INFO[0044] all modules initialized                       bot=internal
INFO[0044] registering modules serve functions ...       bot=internal
INFO[0044] all modules serve functions registered        bot=internal
INFO[0044] starting modules tasks ...                    bot=internal
INFO[0044] tasks running                                 bot=internal

**Comment by ayyz666** [comment]
就是第一次点击登入显示登入成功，但是没有变化，再次点击登入就白屏了

**Comment by ayyz666** [comment]
> 就是第一次点击登入显示登入成功，但是没有变化，再次点击登入就白屏了

| id | name     | data                                                                                                                                                              |
+----+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  1 | bot      | {"account":3283018382,"group_code":0,"password":"xxxxxxx","password_md5":""}                                                                                   |
|  3 | bot_info | {"account":3283018382,"avatar":"https://q2.qlogo.cn/headimg_dl?spec=100\u0026dst_uin=3283018382","group_code":0,"group_list":null,"nick_name":"","on_line":false} |
+----+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------

而且在configs表中删除 bot_info  这行后 进系统设置才不会白屏

**Comment by PBK-B** [comment]
@ayyz666 知道问题了，发了一个最新版你试试这个:  <https://github.com/PBK-B/mirai-class-notice/releases/download/v0.1-Beta/class-notice_linux.tar.gz>

**Comment by ayyz666** [comment]
> @ayyz666 知道问题了，发了一个最新版你试试这个: https://github.com/PBK-B/mirai-class-notice/releases/download/v0.1-Beta/class-notice_linux.tar.gz

OK👌早上起来就试试，大佬早点休息吧😂

**Comment by ayyz666** [comment]
> @ayyz666 知道问题了，发了一个最新版你试试这个: https://github.com/PBK-B/mirai-class-notice/releases/download/v0.1-Beta/class-notice_linux.tar.gz

还是一样白屏，但是第一次点击登入后显示的是登入失败，刷新网页后仍然白屏

**Comment by PBK-B** [comment]
> > @ayyz666 知道问题了，发了一个最新版你试试这个: https://github.com/PBK-B/mirai-class-notice/releases/download/v0.1-Beta/class-notice_linux.tar.gz
> 
> 还是一样白屏，但是第一次点击登入后显示的是登入失败，刷新网页后仍然白屏

好了，我刚刚构建了一个新的 v0.2 版本的，再麻烦你帮忙测试一下

**Comment by ayyz666** [comment]
> > > @ayyz666 知道问题了，发了一个最新版你试试这个: https://github.com/PBK-B/mirai-class-notice/releases/download/v0.1-Beta/class-notice_linux.tar.gz
> > 
> > 
> > 还是一样白屏，但是第一次点击登入后显示的是登入失败，刷新网页后仍然白屏
> 
> 好了，我刚刚构建了一个新的 v0.2 版本的，再麻烦你帮忙测试一下

不知道什么原因在电脑上chrome浏览器点击登入后就白屏，然后我用手机chrome浏览器访问就没问题，但是验证之后登不上，提示失败，请在常用设备上登入

**Comment by ayyz666** [comment]
> > > > @ayyz666 知道问题了，发了一个最新版你试试这个: https://github.com/PBK-B/mirai-class-notice/releases/download/v0.1-Beta/class-notice_linux.tar.gz
> > > 
> > > 
> > > 还是一样白屏，但是第一次点击登入后显示的是登入失败，刷新网页后仍然白屏
> > 
> > 
> > 好了，我刚刚构建了一个新的 v0.2 版本的，再麻烦你帮忙测试一下
> 
> 不知道什么原因在电脑上chrome浏览器点击登入后就白屏，然后我用手机chrome浏览器访问就没问题，但是验证之后登不上，提示失败，请在常用设备上登入

所以白屏应该是浏览器问题，我电脑上换edge就不会白屏了

**Comment by PBK-B** [comment]
> > > > > @ayyz666 知道问题了，发了一个最新版你试试这个: https://github.com/PBK-B/mirai-class-notice/releases/download/v0.1-Beta/class-notice_linux.tar.gz
> > > > 
> > > > 
> > > > 还是一样白屏，但是第一次点击登入后显示的是登入失败，刷新网页后仍然白屏
> > > 
> > > 
> > > 好了，我刚刚构建了一个新的 v0.2 版本的，再麻烦你帮忙测试一下
> > 
> > 
> > 不知道什么原因在电脑上chrome浏览器点击登入后就白屏，然后我用手机chrome浏览器访问就没问题，但是验证之后登不上，提示失败，请在常用设备上登入
> 
> 所以白屏应该是浏览器问题，我电脑上换edge就不会白屏了

v0.2 版本还是会有白屏嘛？安装 v0.2 版本的时候需要将之前的全部文件和数据库先删掉哦

**Comment by ayyz666** [comment]
> > > > > > @ayyz666 知道问题了，发了一个最新版你试试这个: https://github.com/PBK-B/mirai-class-notice/releases/download/v0.1-Beta/class-notice_linux.tar.gz
> > > > > 
> > > > > 
> > > > > 还是一样白屏，但是第一次点击登入后显示的是登入失败，刷新网页后仍然白屏
> > > > 
> > > > 
> > > > 好了，我刚刚构建了一个新的 v0.2 版本的，再麻烦你帮忙测试一下
> > > 
> > > 
> > > 不知道什么原因在电脑上chrome浏览器点击登入后就白屏，然后我用手机chrome浏览器访问就没问题，但是验证之后登不上，提示失败，请在常用设备上登入
> > 
> > 
> > 所以白屏应该是浏览器问题，我电脑上换edge就不会白屏了
> 
> v0.2 版本还是会有白屏嘛？安装 v0.2 版本的时候需要将之前的全部文件和数据库先删掉哦

每次都会删除数据库的，文件也是另外创建的，白屏是应该我这边浏览器出问题，换浏览器就没问题，现在在看怎么登入qq，一直提示异常

**Comment by PBK-B** [comment]
> > > > > > > @ayyz666 知道问题了，发了一个最新版你试试这个: https://github.com/PBK-B/mirai-class-notice/releases/download/v0.1-Beta/class-notice_linux.tar.gz
> > > > > > 
> > > > > > 
> > > > > > 还是一样白屏，但是第一次点击登入后显示的是登入失败，刷新网页后仍然白屏
> > > > > 
> > > > > 
> > > > > 好了，我刚刚构建了一个新的 v0.2 版本的，再麻烦你帮忙测试一下
> > > > 
> > > > 
> > > > 不知道什么原因在电脑上chrome浏览器点击登入后就白屏，然后我用手机chrome浏览器访问就没问题，但是验证之后登不上，提示失败，请在常用设备上登入
> > > 
> > > 
> > > 所以白屏应该是浏览器问题，我电脑上换edge就不会白屏了
> > 
> > 
> > v0.2 版本还是会有白屏嘛？安装 v0.2 版本的时候需要将之前的全部文件和数据库先删掉哦
> 
> 每次都会删除数据库的，文件也是另外创建的，白屏是应该我这边浏览器出问题，换浏览器就没问题，现在在看怎么登入qq，一直提示异常

我加一下你 QQ 吧？你把你搭建好的地址发我我登陆看看报啥错误

**Comment by ayyz666** [comment]
> > > > > > > > @ayyz666 知道问题了，发了一个最新版你试试这个: https://github.com/PBK-B/mirai-class-notice/releases/download/v0.1-Beta/class-notice_linux.tar.gz
> > > > > > > 
> > > > > > > 
> > > > > > > 还是一样白屏，但是第一次点击登入后显示的是登入失败，刷新网页后仍然白屏
> > > > > > 
> > > > > > 
> > > > > > 好了，我刚刚构建了一个新的 v0.2 版本的，再麻烦你帮忙测试一下
> > > > > 
> > > > > 
> > > > > 不知道什么原因在电脑上chrome浏览器点击登入后就白屏，然后我用手机chrome浏览器访问就没问题，但是验证之后登不上，提示失败，请在常用设备上登入
> > > > 
> > > > 
> > > > 所以白屏应该是浏览器问题，我电脑上换edge就不会白屏了
> > > 
> > > 
> > > v0.2 版本还是会有白屏嘛？安装 v0.2 版本的时候需要将之前的全部文件和数据库先删掉哦
> > 
> > 
> > 每次都会删除数据库的，文件也是另外创建的，白屏是应该我这边浏览器出问题，换浏览器就没问题，现在在看怎么登入qq，一直提示异常
> 
> 我加一下你 QQ 吧？你把你搭建好的地址发我我登陆看看报啥错误

1826153589
