### ISSUE TITLE
nohup: 忽略输入并把输出追加到'nohup.out' 

### ISSUE THREAD

**Issue by 778147282** [PBK-B/mirai-class-notice#5]
[AzureUser@xuyao class_notice]$ nohup ./class_notice &
[1] 1958601
[AzureUser@xuyao class_notice]$ nohup: 忽略输入并把输出追加到'nohup.out'
大佬 这是什么原因

**Comment by FW27623** [comment]
这个都是这样的，这个是把日志输出到nohup.out这个文件里了，你可以去看看项目能不能访问

**Comment by 778147282** [comment]
> 
> 
> 这个都是这样的，这个是把日志输出到nohup.out这个文件里了，你可以去看看项目能不能访问

谢谢好哥哥
