### ISSUE TITLE
关于下载压缩包报错404

### ISSUE THREAD

**Issue by sbcxk** [PBK-B/mirai-class-notice#6]
文档第二步下载压缩包报错404 nofound，求助

**Comment by FW27623** [comment]
用 `wget https://github.com/PBK-B/mirai-class-notice/releases/download/v0.1-Beta/class-notice_linux_amd64.tar.gz` 试试

**Comment by FW27623** [comment]
> 用 `wget https://github.com/PBK-B/mirai-class-notice/releases/download/v0.1-Beta/class-notice_linux_amd64.tar.gz` 试试

如果不行，看看你的机子是不是能够正常访问github,不行就手动上传文件到服务器

**Comment by sbcxk** [comment]
![image](https://user-images.githubusercontent.com/67060479/130818049-879e39df-c616-4c5c-b106-bb6d1c6df5fe.png)
[1]+  Exit 2 这里报了个这个，不太懂什么意思，大佬能看一下吗

**Comment by PBK-B** [comment]
> ![image](https://user-images.githubusercontent.com/67060479/130818049-879e39df-c616-4c5c-b106-bb6d1c6df5fe.png)
> [1]+ Exit 2 这里报了个这个，不太懂什么意思，大佬能看一下吗

能访问 `http://ip:8089/admin` 后台了嘛？
