### ISSUE TITLE
登陆QQ后，再打开后台，点系统设置时界面白屏，其他的功能如课表什么的都能设置

### ISSUE THREAD

**Issue by OnePerson2020** [PBK-B/mirai-class-notice#8]
登陆QQ后，再打开后台，点系统设置时界面白屏，其他的功能如课表什么的都能设置

**Comment by PBK-B** [comment]
收到，在修了

**Comment by PBK-B** [comment]
@OnePerson2020 v0.2 版本已经修复啦，可以试试呢    <https://github.com/PBK-B/mirai-class-notice/releases/download/v0.2-Beta/class-notice_linux.tar.gz>

**Comment by OnePerson2020** [comment]
> @OnePerson2020 v0.2 版本已经修复啦，可以试试呢 https://github.com/PBK-B/mirai-class-notice/releases/download/v0.2-Beta/class-notice_linux.tar.gz

       非常感谢您快速的回答， 但是出现了另外一个问题，输入完ticket后，提示:(其他登陆错误) login failed: 当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。
       请问这种情况要怎么办呀，已经试过更换过device.json了
       在后台界面，已经能看到头像

**Comment by PBK-B** [comment]
> > @OnePerson2020 v0.2 版本已经修复啦，可以试试呢 https://github.com/PBK-B/mirai-class-notice/releases/download/v0.2-Beta/class-notice_linux.tar.gz
> 
> ```
>    非常感谢您快速的回答， 但是出现了另外一个问题，输入完ticket后，提示:(其他登陆错误) login failed: 当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。
>    请问这种情况要怎么办呀，已经试过更换过device.json了
>    在后台界面，已经能看到头像
> ```

我刚刚编译了一个新的 linux 版本 class-notice_linux.tar.gz 文件已经上传了，我想应该修复了这个问题，可以帮忙测试一下吗？

**Comment by OnePerson2020** [comment]
你好，我还是出现了之前的问题，我用浏览器得到的ticket是这样的，是我的ticket有问题吗？t03hzvtjIlCaNAG6OT23VReIrerW88jIb2Hwx7JDx_g1AzyMZBIwtXv9-7NC87b_MzA0V7lxvxKwQOzxfc1D_guU9FhqI-vvph5m4h-QEXQjhG7lxwkkRqm8X-zctduM58SM9CJ4wNI5vEwf3po9_Oe5xTnejO0RIOfQk6zpx4k3-EJivEqaY3mXw**









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PBK-B/mirai-class-notice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月26日(星期四) 下午5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PBK-B/mirai-class-notice] 登陆QQ后，再打开后台，点系统设置时界面白屏，其他的功能如课表什么的都能设置 (#8)





   
@OnePerson2020 v0.2 版本已经修复啦，可以试试呢 https://github.com/PBK-B/mirai-class-notice/releases/download/v0.2-Beta/class-notice_linux.tar.gz
     非常感谢您快速的回答， 但是出现了另外一个问题，输入完ticket后，提示:(其他登陆错误) login failed: 当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。    请问这种情况要怎么办呀，已经试过更换过device.json了    在后台界面，已经能看到头像   
我刚刚编译了一个新的 linux 版本 class-notice_linux.tar.gz 文件已经上传了，我想应该修复了这个问题，可以帮忙测试一下吗？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PBK-B** [comment]
> 你好，我还是出现了之前的问题，我用浏览器得到的ticket是这样的，是我的ticket有问题吗？t03hzvtjIlCaNAG6OT23VReIrerW88jIb2Hwx7JDx_g1AzyMZBIwtXv9-7NC87b_MzA0V7lxvxKwQOzxfc1D_guU9FhqI-vvph5m4h-QEXQjhG7lxwkkRqm8X-zctduM58SM9CJ4wNI5vEwf3po9_Oe5xTnejO0RIOfQk6zpx4k3-EJivEqaY3mXw**
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PBK-B/mirai-class-notice" ***@***.***&gt;; 发送时间:&nbsp;2021年8月26日(星期四) 下午5:28 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PBK-B/mirai-class-notice] 登陆QQ后，再打开后台，点系统设置时界面白屏，其他的功能如课表什么的都能设置 (#8) @OnePerson2020 v0.2 版本已经修复啦，可以试试呢 https://github.com/PBK-B/mirai-class-notice/releases/download/v0.2-Beta/class-notice_linux.tar.gz 非常感谢您快速的回答， 但是出现了另外一个问题，输入完ticket后，提示:(其他登陆错误) login failed: 当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。 请问这种情况要怎么办呀，已经试过更换过device.json了 在后台界面，已经能看到头像 我刚刚编译了一个新的 linux 版本 class-notice_linux.tar.gz 文件已经上传了，我想应该修复了这个问题，可以帮忙测试一下吗？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

换了 device.json 嘛？贴一下运行日志吧。

**Comment by OnePerson2020** [comment]
WARN[0000] stopping ...&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; bot=internal
INFO[0000] stopped&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;bot=internal
【Model.go】注册数据模型
table `users` already exists, skip
table `configs` already exists, skip
table `accounts` already exists, skip
table `times` already exists, skip
table `courses` already exists, skip
2021/08/27 09:22:39 【models.Time】注册全部上课时间定时任务成功！
2021/08/27 09:22:39.827 [I] [server.go:241]&nbsp; http server Running on http://0.0.0.0:8089


INFO[0008] initializing modules ...&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; bot=internal
INFO[0008] all modules initialized&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;bot=internal
INFO[0008] registering modules serve functions ...&nbsp; &nbsp; &nbsp; &nbsp;bot=internal
INFO[0008] all modules serve functions registered&nbsp; &nbsp; &nbsp; &nbsp; bot=internal
INFO[0008] starting modules tasks ...&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; bot=internal
INFO[0008] tasks running&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;bot=internal
[botLog] use user device.json flie…
[botLog] device.json error





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PBK-B/mirai-class-notice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月27日(星期五) 上午9:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PBK-B/mirai-class-notice] 登陆QQ后，再打开后台，点系统设置时界面白屏，其他的功能如课表什么的都能设置 (#8)





  
你好，我还是出现了之前的问题，我用浏览器得到的ticket是这样的，是我的ticket有问题吗？t03hzvtjIlCaNAG6OT23VReIrerW88jIb2Hwx7JDx_g1AzyMZBIwtXv9-7NC87b_MzA0V7lxvxKwQOzxfc1D_guU9FhqI-vvph5m4h-QEXQjhG7lxwkkRqm8X-zctduM58SM9CJ4wNI5vEwf3po9_Oe5xTnejO0RIOfQk6zpx4k3-EJivEqaY3mXw**
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PBK-B/mirai-class-notice" @.&gt;; 发送时间:&nbsp;2021年8月26日(星期四) 下午5:28 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [PBK-B/mirai-class-notice] 登陆QQ后，再打开后台，点系统设置时界面白屏，其他的功能如课表什么的都能设置 (#8) @OnePerson2020 v0.2 版本已经修复啦，可以试试呢 https://github.com/PBK-B/mirai-class-notice/releases/download/v0.2-Beta/class-notice_linux.tar.gz 非常感谢您快速的回答， 但是出现了另外一个问题，输入完ticket后，提示:(其他登陆错误) login failed: 当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。 请问这种情况要怎么办呀，已经试过更换过device.json了 在后台界面，已经能看到头像 我刚刚编译了一个新的 linux 版本 class-notice_linux.tar.gz 文件已经上传了，我想应该修复了这个问题，可以帮忙测试一下吗？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
换了 device.json 嘛？贴一下运行日志吧。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PBK-B** [comment]
> [botLog] device.json error

device.json 替换了嘛？日志中显示 device.json 加载错误

**Comment by OnePerson2020** [comment]
> > [botLog] device.json error
> 
> device.json 替换了嘛？日志中显示 device.json 加载错误

替换手机的不行，刚刚先用电脑端登陆了一下go-cqhttp ，然后把电脑端的device.json替换，登陆成功了。但是我的账号风控了，发消息的功能还测试不了

**Comment by PBK-B** [comment]
> > > [botLog] device.json error
> > 
> > 
> > device.json 替换了嘛？日志中显示 device.json 加载错误
> 
> 替换手机的不行，刚刚先用电脑端登陆了一下go-cqhttp ，然后把电脑端的device.json替换，登陆成功了。但是我的账号风控了，发消息的功能还测试不了

现在登陆成功了是吧？你创建一个上课时间为待会 10:20 的，然后添加一个课程使用该时间。然后点击上课时间后面的通知来手动触发课程通知（记得设置里面选择好需要通知的 QQ 群聊）。

**Comment by OnePerson2020** [comment]
手动触发成功了。但是现在有一个疑问，如果让提醒自动触发呢。因为上课时间的设置是自己手动写的，时间要写成怎样的格式才能触发自动提醒呢。写成12小时制还是24小时制，中间用中文：还是英文:




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PBK-B/mirai-class-notice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月27日(星期五) 上午9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PBK-B/mirai-class-notice] 登陆QQ后，再打开后台，点系统设置时界面白屏，其他的功能如课表什么的都能设置 (#8)





    
[botLog] device.json error
  
device.json 替换了嘛？日志中显示 device.json 加载错误
  
替换手机的不行，刚刚先用电脑端登陆了一下go-cqhttp ，然后把电脑端的device.json替换，登陆成功了。但是我的账号风控了，发消息的功能还测试不了
  
现在登陆成功了是吧？你创建一个上课时间为待会 10:20 的，然后添加一个课程使用该时间。然后点击上课时间后面的通知来手动触发课程通知（记得设置里面选择好需要通知的 QQ 群聊）。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PBK-B** [comment]
> 手动触发成功了。但是现在有一个疑问，如果让提醒自动触发呢。因为上课时间的设置是自己手动写的，时间要写成怎样的格式才能触发自动提醒呢。写成12小时制还是24小时制，中间用中文：还是英文:
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PBK-B/mirai-class-notice" ***@***.***&gt;; 发送时间:&nbsp;2021年8月27日(星期五) 上午9:46 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PBK-B/mirai-class-notice] 登陆QQ后，再打开后台，点系统设置时界面白屏，其他的功能如课表什么的都能设置 (#8) [botLog] device.json error device.json 替换了嘛？日志中显示 device.json 加载错误 替换手机的不行，刚刚先用电脑端登陆了一下go-cqhttp ，然后把电脑端的device.json替换，登陆成功了。但是我的账号风控了，发消息的功能还测试不了 现在登陆成功了是吧？你创建一个上课时间为待会 10:20 的，然后添加一个课程使用该时间。然后点击上课时间后面的通知来手动触发课程通知（记得设置里面选择好需要通知的 QQ 群聊）。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

设置中有个提前多少分钟触发自动通知的选项。把上课时间（24 小时制，使用英文 : 分隔，例如  23:59  ）全部设定好之后，点击上课时间列表上方的重置定时（修改了设置中的提前多少分钟触发通知选项的话也需要重新重置定时任务哦），然后添加课程就好啦（可以给同学或者朋友创建一个账号让他们帮忙添加课程哦，我就是这么干的 🐶  ）。

**Comment by ALin596** [comment]
> > > [botLog] device.json error
> > 
> > 
> > device.json 替换了嘛？日志中显示 device.json 加载错误
> 
> 替换手机的不行，刚刚先用电脑端登陆了一下go-cqhttp ，然后把电脑端的device.json替换，登陆成功了。但是我的账号风控了，发消息的功能还测试不了

老哥我在电脑端用go-cqhttp登录之后生成的文件，替换之后没有效果啊...

**Comment by OnePerson2020** [comment]
> > > > [botLog] device.json error
> > > 
> > > 
> > > device.json 替换了嘛？日志中显示 device.json 加载错误
> > 
> > 
> > 替换手机的不行，刚刚先用电脑端登陆了一下go-cqhttp ，然后把电脑端的device.json替换，登陆成功了。但是我的账号风控了，发消息的功能还测试不了
> 
> 老哥我在电脑端用go-cqhttp登录之后生成的文件，替换之后没有效果啊...

你可以试一下服务器先登一下go-cqhttp然后用这里生成的device.json

**Comment by ALin596** [comment]
> > > > > [botLog] device.json error
> > > > 
> > > > 
> > > > device.json 替换了嘛？日志中显示 device.json 加载错误
> > > 
> > > 
> > > 替换手机的不行，刚刚先用电脑端登陆了一下go-cqhttp ，然后把电脑端的device.json替换，登陆成功了。但是我的账号风控了，发消息的功能还测试不了
> > 
> > 
> > 老哥我在电脑端用go-cqhttp登录之后生成的文件，替换之后没有效果啊...
> 
> 你可以试一下服务器先登一下go-cqhttp然后用这里生成的device.json

我使用了http通信，iPad协议在服务器登录上QQ了，然后把cphttp目录下的device.json粘贴到classs_notice目录下
尝试进入后台登QQ，还是提示错误
页面提示：QQ 账号登陆异常，Packet timed out
下面是错误日志
```
2021-08-28T23:36:08: time="2021-08-28T23:36:08+08:00" level=info msg="initializing modules ..." bot=internal
2021-08-28T23:36:08: time="2021-08-28T23:36:08+08:00" level=info msg="all modules initialized" bot=internal
2021-08-28T23:36:08: time="2021-08-28T23:36:08+08:00" level=info msg="registering modules serve functions ..." bot=internal
2021-08-28T23:36:08: time="2021-08-28T23:36:08+08:00" level=info msg="all modules serve functions registered" bot=internal
2021-08-28T23:36:08: time="2021-08-28T23:36:08+08:00" level=info msg="starting modules tasks ..." bot=internal
2021-08-28T23:36:08: time="2021-08-28T23:36:08+08:00" level=info msg="tasks running" bot=internal

```
