### ISSUE TITLE
配置文件修改内容

### ISSUE THREAD

**Issue by ALin596** [PBK-B/mirai-class-notice#9]
appname = class_notice
httpaddr = 服务器公网ip
httpport = 8089
runmode = prod
dbhost = 127.0.0.1:3306
dbdriver = mysql
dbusername = 数据库名
dbpassword = 数据库密码
dbdatabase = test_class_notice

老哥 这个配置文件我是这么配置的，但是后台地址打不开怎么处理（已经放行了端口号）

**Comment by ALin596** [comment]
![image](https://user-images.githubusercontent.com/73337768/130824637-a9d1e511-6ad6-40d3-9182-d623e15fc87b.png)
还有就是报了nohup: ignoring input and appending output to 'nohup.out'
我百度了一下把命令改成了nohup ./class_notice >/dev/null 2>/dev/null &
会不会是这个的问题

**Comment by sbcxk** [comment]
我也是这个问题，同问请教了

**Comment by PBK-B** [comment]
> appname = class_notice
> httpaddr = 服务器公网ip
> httpport = 8089
> runmode = prod
> dbhost = 127.0.0.1:3306
> dbdriver = mysql
> dbusername = 数据库名
> dbpassword = 数据库密码
> dbdatabase = test_class_notice
> 
> 老哥 这个配置文件我是这么配置的，但是后台地址打不开怎么处理（已经放行了端口号）

httpaddr 不用设置公网 IP 呀，设置 0.0.0.0 就好了

**Comment by ALin596** [comment]
> > appname = class_notice
> > httpaddr = 服务器公网ip
> > httpport = 8089
> > runmode = prod
> > dbhost = 127.0.0.1:3306
> > dbdriver = mysql
> > dbusername = 数据库名
> > dbpassword = 数据库密码
> > dbdatabase = test_class_notice
> > 老哥 这个配置文件我是这么配置的，但是后台地址打不开怎么处理（已经放行了端口号）
> 
> httpaddr 不用设置公网 IP 呀，设置 0.0.0.0 就好了

改成0.0.0.0还是不行
这是日志你看下.....
![image](https://user-images.githubusercontent.com/73337768/130842673-8d36c1f8-cc0a-4a44-8073-6e735f18cc53.png)

**Comment by PBK-B** [comment]
> > > appname = class_notice
> > > httpaddr = 服务器公网ip
> > > httpport = 8089
> > > runmode = prod
> > > dbhost = 127.0.0.1:3306
> > > dbdriver = mysql
> > > dbusername = 数据库名
> > > dbpassword = 数据库密码
> > > dbdatabase = test_class_notice
> > > 老哥 这个配置文件我是这么配置的，但是后台地址打不开怎么处理（已经放行了端口号）
> > 
> > 
> > httpaddr 不用设置公网 IP 呀，设置 0.0.0.0 就好了
> 
> 改成0.0.0.0还是不行
> 这是日志你看下.....
> ![image](https://user-images.githubusercontent.com/73337768/130842673-8d36c1f8-cc0a-4a44-8073-6e735f18cc53.png)

这是数据库连接失败

**Comment by ALin596** [comment]
还是不行，我重新删除、解压，全部使用你教程给的命令，进不去后台
这是我的配置文件
![image](https://user-images.githubusercontent.com/73337768/130890813-a6c19d55-22c3-4d0c-8b5b-00168f00f24b.png)
如果用nohup ./class_notice &的话，nohup.out文件是空的

**Comment by PBK-B** [comment]
> 还是不行，我重新删除、解压，全部使用你教程给的命令，进不去后台
> 这是我的配置文件
> ![image](https://user-images.githubusercontent.com/73337768/130890813-a6c19d55-22c3-4d0c-8b5b-00168f00f24b.png)
> 如果用nohup ./class_notice &的话，nohup.out文件是空的

直接执行
```
./class_notice
```
还是报错数据库问题嘛？
用我刚刚发布的 v0.2 Beta 版试试

**Comment by ALin596** [comment]
> > 还是不行，我重新删除、解压，全部使用你教程给的命令，进不去后台
> > 这是我的配置文件
> > ![image](https://user-images.githubusercontent.com/73337768/130890813-a6c19d55-22c3-4d0c-8b5b-00168f00f24b.png)
> > 如果用nohup ./class_notice &的话，nohup.out文件是空的
> 
> 直接执行
> 
> ```
> ./class_notice
> ```
> 
> 还是报错数据库问题嘛？
> 用我刚刚发布的 v0.2 Beta 版试试

还是不可以....
我给你讲一下我的操作流程
1、宝塔进入root下，手动创建了一个class_notice
2、把新版本class-notice_linux.tar.gz上传到class_notice文件夹并解压
3、手动进入conf，修改配置文件，只更改了你的帮助文档中的dbusername和dbpassword，改为我自己数据库名和密码
4、输入./class_notice，提示
`-bash: ./class_notice: Is a directory`
输入nohup ./class_notice &，提示
```
[root@iZuf6erq7yws01gygl3zw0Z ~]# nohup ./class_notice &
[1] 4888
[root@iZuf6erq7yws01gygl3zw0Z ~]# nohup: ignoring input and appending output to 'nohup.out'
nohup: failed to run command './class_notice': Permission denied
```
看不懂，再次回车后，提示
```
[1]+  Exit 126                nohup ./class_notice
```
5、尝试访问后台，进不去
6、class_notice里面没有nohup.out，这个输出文件是在root目录下，权限为600，里面什么都没有

**Comment by PBK-B** [comment]
> > > 还是不行，我重新删除、解压，全部使用你教程给的命令，进不去后台
> > > 这是我的配置文件
> > > ![image](https://user-images.githubusercontent.com/73337768/130890813-a6c19d55-22c3-4d0c-8b5b-00168f00f24b.png)
> > > 如果用nohup ./class_notice &的话，nohup.out文件是空的
> > 
> > 
> > 直接执行
> > ```
> > ./class_notice
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 还是报错数据库问题嘛？
> > 用我刚刚发布的 v0.2 Beta 版试试
> 
> 还是不可以....
> 我给你讲一下我的操作流程
> 1、宝塔进入root下，手动创建了一个class_notice
> 2、把新版本class-notice_linux.tar.gz上传到class_notice文件夹并解压
> 3、手动进入conf，修改配置文件，只更改了你的帮助文档中的dbusername和dbpassword，改为我自己数据库名和密码
> 4、输入./class_notice，提示
> `-bash: ./class_notice: Is a directory`
> 输入nohup ./class_notice &，提示
> 
> ```
> [root@iZuf6erq7yws01gygl3zw0Z ~]# nohup ./class_notice &
> [1] 4888
> [root@iZuf6erq7yws01gygl3zw0Z ~]# nohup: ignoring input and appending output to 'nohup.out'
> nohup: failed to run command './class_notice': Permission denied
> ```
> 
> 看不懂，再次回车后，提示
> 
> ```
> [1]+  Exit 126                nohup ./class_notice
> ```
> 
> 5、尝试访问后台，进不去
> 6、class_notice里面没有nohup.out，这个输出文件是在root目录下，权限为600，里面什么都没有

你需要先 `cd class_notice` 进入到 class_notice 目录下再执行 `./class_notice`

**Comment by ALin596** [comment]
> > > > 还是不行，我重新删除、解压，全部使用你教程给的命令，进不去后台
> > > > 这是我的配置文件
> > > > ![image](https://user-images.githubusercontent.com/73337768/130890813-a6c19d55-22c3-4d0c-8b5b-00168f00f24b.png)
> > > > 如果用nohup ./class_notice &的话，nohup.out文件是空的
> > > 
> > > 
> > > 直接执行
> > > ```
> > > ./class_notice
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 还是报错数据库问题嘛？
> > > 用我刚刚发布的 v0.2 Beta 版试试
> > 
> > 
> > 还是不可以....
> > 我给你讲一下我的操作流程
> > 1、宝塔进入root下，手动创建了一个class_notice
> > 2、把新版本class-notice_linux.tar.gz上传到class_notice文件夹并解压
> > 3、手动进入conf，修改配置文件，只更改了你的帮助文档中的dbusername和dbpassword，改为我自己数据库名和密码
> > 4、输入./class_notice，提示
> > `-bash: ./class_notice: Is a directory`
> > 输入nohup ./class_notice &，提示
> > ```
> > [root@iZuf6erq7yws01gygl3zw0Z ~]# nohup ./class_notice &
> > [1] 4888
> > [root@iZuf6erq7yws01gygl3zw0Z ~]# nohup: ignoring input and appending output to 'nohup.out'
> > nohup: failed to run command './class_notice': Permission denied
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 看不懂，再次回车后，提示
> > ```
> > [1]+  Exit 126                nohup ./class_notice
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 5、尝试访问后台，进不去
> > 6、class_notice里面没有nohup.out，这个输出文件是在root目录下，权限为600，里面什么都没有
> 
> 你需要先 `cd class_notice` 进入到 class_notice 目录下再执行 `./class_notice`

emmm，看不懂😭😭
```
[root@iZuf6erq7yws01gygl3zw0Z ~]# cd class_notice
[root@iZuf6erq7yws01gygl3zw0Z class_notice]# ./class_notice
2021/08/26 12:24:47.976 [W]  init global config instance failed. If you donot use this, just ignore it.  open conf/app.conf: no such file or directory

WARN[0000] stopping ...                                  bot=internal
INFO[0000] stopped                                       bot=internal
[ORM]2021/08/26 12:24:47 register db `default`, sql: unknown driver "" (forgotten import?)
【Model.go】注册数据模型
must have one register DataBase alias named `default`
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0x36, 0x0, 0x0)
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/debug/stack.go:16 +0x25
github.com/beego/beego/v2/client/orm.(*_modelCache).bootstrap(0xc00007a140)
        /Users/bin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/models.go:327 +0x4d7
github.com/beego/beego/v2/client/orm.BootStrap(...)
        /Users/bin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/models_boot.go:39
github.com/beego/beego/v2/client/orm.RunSyncdb(0xf99ee7, 0x7, 0x100, 0x1, 0xc0000f7c08)
        /Users/bin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/cmd.go:289 +0x31
class_notice/models.init.3()
        /Volumes/tzmaxData/data/web/class_notice/models/default.go:56 +0x57b
panic: unknown DataBase alias name default

goroutine 1 [running]:
github.com/beego/beego/v2/client/orm.getDbAlias(0xf99ee7, 0x7, 0xc0002c2510)
        /Users/bin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/db_utils.go:28 +0xf1
github.com/beego/beego/v2/client/orm.RunSyncdb(0xf99ee7, 0x7, 0x100, 0x1, 0xc0000f7c08)
        /Users/bin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/cmd.go:291 +0x49
class_notice/models.init.3()
        /Volumes/tzmaxData/data/web/class_notice/models/default.go:56 +0x57b
```

**Comment by PBK-B** [comment]
> > > > > 还是不行，我重新删除、解压，全部使用你教程给的命令，进不去后台
> > > > > 这是我的配置文件
> > > > > ![image](https://user-images.githubusercontent.com/73337768/130890813-a6c19d55-22c3-4d0c-8b5b-00168f00f24b.png)
> > > > > 如果用nohup ./class_notice &的话，nohup.out文件是空的
> > > > 
> > > > 
> > > > 直接执行
> > > > ```
> > > > ./class_notice
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 还是报错数据库问题嘛？
> > > > 用我刚刚发布的 v0.2 Beta 版试试
> > > 
> > > 
> > > 还是不可以....
> > > 我给你讲一下我的操作流程
> > > 1、宝塔进入root下，手动创建了一个class_notice
> > > 2、把新版本class-notice_linux.tar.gz上传到class_notice文件夹并解压
> > > 3、手动进入conf，修改配置文件，只更改了你的帮助文档中的dbusername和dbpassword，改为我自己数据库名和密码
> > > 4、输入./class_notice，提示
> > > `-bash: ./class_notice: Is a directory`
> > > 输入nohup ./class_notice &，提示
> > > ```
> > > [root@iZuf6erq7yws01gygl3zw0Z ~]# nohup ./class_notice &
> > > [1] 4888
> > > [root@iZuf6erq7yws01gygl3zw0Z ~]# nohup: ignoring input and appending output to 'nohup.out'
> > > nohup: failed to run command './class_notice': Permission denied
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 看不懂，再次回车后，提示
> > > ```
> > > [1]+  Exit 126                nohup ./class_notice
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 5、尝试访问后台，进不去
> > > 6、class_notice里面没有nohup.out，这个输出文件是在root目录下，权限为600，里面什么都没有
> > 
> > 
> > 你需要先 `cd class_notice` 进入到 class_notice 目录下再执行 `./class_notice`
> 
> emmm，看不懂😭😭
> 
> ```
> [root@iZuf6erq7yws01gygl3zw0Z ~]# cd class_notice
> [root@iZuf6erq7yws01gygl3zw0Z class_notice]# ./class_notice
> 2021/08/26 12:24:47.976 [W]  init global config instance failed. If you donot use this, just ignore it.  open conf/app.conf: no such file or directory
> 
> WARN[0000] stopping ...                                  bot=internal
> INFO[0000] stopped                                       bot=internal
> [ORM]2021/08/26 12:24:47 register db `default`, sql: unknown driver "" (forgotten import?)
> 【Model.go】注册数据模型
> must have one register DataBase alias named `default`
> goroutine 1 [running, locked to thread]:
> runtime/debug.Stack(0x36, 0x0, 0x0)
>         /usr/local/Cellar/go/1.16.5/libexec/src/runtime/debug/stack.go:24 +0x9f
> runtime/debug.PrintStack()
>         /usr/local/Cellar/go/1.16.5/libexec/src/runtime/debug/stack.go:16 +0x25
> github.com/beego/beego/v2/client/orm.(*_modelCache).bootstrap(0xc00007a140)
>         /Users/bin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/models.go:327 +0x4d7
> github.com/beego/beego/v2/client/orm.BootStrap(...)
>         /Users/bin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/models_boot.go:39
> github.com/beego/beego/v2/client/orm.RunSyncdb(0xf99ee7, 0x7, 0x100, 0x1, 0xc0000f7c08)
>         /Users/bin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/cmd.go:289 +0x31
> class_notice/models.init.3()
>         /Volumes/tzmaxData/data/web/class_notice/models/default.go:56 +0x57b
> panic: unknown DataBase alias name default
> 
> goroutine 1 [running]:
> github.com/beego/beego/v2/client/orm.getDbAlias(0xf99ee7, 0x7, 0xc0002c2510)
>         /Users/bin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/db_utils.go:28 +0xf1
> github.com/beego/beego/v2/client/orm.RunSyncdb(0xf99ee7, 0x7, 0x100, 0x1, 0xc0000f7c08)
>         /Users/bin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/cmd.go:291 +0x49
> class_notice/models.init.3()
>         /Volumes/tzmaxData/data/web/class_notice/models/default.go:56 +0x57b
> ```

这是 mysql 数据库没有连接上鸭，你数据库账号密码啥的没有弄错嘛？

**Comment by ayyz666** [comment]
> appname = class_notice
> httpaddr = 服务器公网ip
> httpport = 8089
> runmode = prod
> dbhost = 127.0.0.1:3306
> dbdriver = mysql
> dbusername = 数据库名
> dbpassword = 数据库密码
> dbdatabase = test_class_notice
> 
> 老哥 这个配置文件我是这么配置的，但是后台地址打不开怎么处理（已经放行了端口号）

你创建一个名字叫 test_class_notice 的数据库就能运行了

**Comment by ALin596** [comment]
> > appname = class_notice
> > httpaddr = 服务器公网ip
> > httpport = 8089
> > runmode = prod
> > dbhost = 127.0.0.1:3306
> > dbdriver = mysql
> > dbusername = 数据库名
> > dbpassword = 数据库密码
> > dbdatabase = test_class_notice
> > 老哥 这个配置文件我是这么配置的，但是后台地址打不开怎么处理（已经放行了端口号）
> 
> 你创建一个名字叫 test_class_notice 的数据库就能运行了

是这样创建吗？
![image](https://user-images.githubusercontent.com/73337768/130906673-aab5f23e-6ce9-4b9f-a220-4ccb88cdea60.png)

**Comment by ALin596** [comment]
> > > > > > 还是不行，我重新删除、解压，全部使用你教程给的命令，进不去后台
> > > > > > 这是我的配置文件
> > > > > > ![image](https://user-images.githubusercontent.com/73337768/130890813-a6c19d55-22c3-4d0c-8b5b-00168f00f24b.png)
> > > > > > 如果用nohup ./class_notice &的话，nohup.out文件是空的
> > > > > 
> > > > > 
> > > > > 直接执行
> > > > > ```
> > > > > ./class_notice
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 还是报错数据库问题嘛？
> > > > > 用我刚刚发布的 v0.2 Beta 版试试
> > > > 
> > > > 
> > > > 还是不可以....
> > > > 我给你讲一下我的操作流程
> > > > 1、宝塔进入root下，手动创建了一个class_notice
> > > > 2、把新版本class-notice_linux.tar.gz上传到class_notice文件夹并解压
> > > > 3、手动进入conf，修改配置文件，只更改了你的帮助文档中的dbusername和dbpassword，改为我自己数据库名和密码
> > > > 4、输入./class_notice，提示
> > > > `-bash: ./class_notice: Is a directory`
> > > > 输入nohup ./class_notice &，提示
> > > > ```
> > > > [root@iZuf6erq7yws01gygl3zw0Z ~]# nohup ./class_notice &
> > > > [1] 4888
> > > > [root@iZuf6erq7yws01gygl3zw0Z ~]# nohup: ignoring input and appending output to 'nohup.out'
> > > > nohup: failed to run command './class_notice': Permission denied
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 看不懂，再次回车后，提示
> > > > ```
> > > > [1]+  Exit 126                nohup ./class_notice
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 5、尝试访问后台，进不去
> > > > 6、class_notice里面没有nohup.out，这个输出文件是在root目录下，权限为600，里面什么都没有
> > > 
> > > 
> > > 你需要先 `cd class_notice` 进入到 class_notice 目录下再执行 `./class_notice`
> > 
> > 
> > emmm，看不懂😭😭
> > ```
> > [root@iZuf6erq7yws01gygl3zw0Z ~]# cd class_notice
> > [root@iZuf6erq7yws01gygl3zw0Z class_notice]# ./class_notice
> > 2021/08/26 12:24:47.976 [W]  init global config instance failed. If you donot use this, just ignore it.  open conf/app.conf: no such file or directory
> > 
> > WARN[0000] stopping ...                                  bot=internal
> > INFO[0000] stopped                                       bot=internal
> > [ORM]2021/08/26 12:24:47 register db `default`, sql: unknown driver "" (forgotten import?)
> > 【Model.go】注册数据模型
> > must have one register DataBase alias named `default`
> > goroutine 1 [running, locked to thread]:
> > runtime/debug.Stack(0x36, 0x0, 0x0)
> >         /usr/local/Cellar/go/1.16.5/libexec/src/runtime/debug/stack.go:24 +0x9f
> > runtime/debug.PrintStack()
> >         /usr/local/Cellar/go/1.16.5/libexec/src/runtime/debug/stack.go:16 +0x25
> > github.com/beego/beego/v2/client/orm.(*_modelCache).bootstrap(0xc00007a140)
> >         /Users/bin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/models.go:327 +0x4d7
> > github.com/beego/beego/v2/client/orm.BootStrap(...)
> >         /Users/bin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/models_boot.go:39
> > github.com/beego/beego/v2/client/orm.RunSyncdb(0xf99ee7, 0x7, 0x100, 0x1, 0xc0000f7c08)
> >         /Users/bin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/cmd.go:289 +0x31
> > class_notice/models.init.3()
> >         /Volumes/tzmaxData/data/web/class_notice/models/default.go:56 +0x57b
> > panic: unknown DataBase alias name default
> > 
> > goroutine 1 [running]:
> > github.com/beego/beego/v2/client/orm.getDbAlias(0xf99ee7, 0x7, 0xc0002c2510)
> >         /Users/bin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/db_utils.go:28 +0xf1
> > github.com/beego/beego/v2/client/orm.RunSyncdb(0xf99ee7, 0x7, 0x100, 0x1, 0xc0000f7c08)
> >         /Users/bin/go/pkg/mod/github.com/beego/beego/v2@v2.0.1/client/orm/cmd.go:291 +0x49
> > class_notice/models.init.3()
> >         /Volumes/tzmaxData/data/web/class_notice/models/default.go:56 +0x57b
> > ```
> 
> 这是 mysql 数据库没有连接上鸭，你数据库账号密码啥的没有弄错嘛？

不会出错，我都是复制粘贴的...

**Comment by ayyz666** [comment]
> > > appname = class_notice
> > > httpaddr = 服务器公网ip
> > > httpport = 8089
> > > runmode = prod
> > > dbhost = 127.0.0.1:3306
> > > dbdriver = mysql
> > > dbusername = 数据库名
> > > dbpassword = 数据库密码
> > > dbdatabase = test_class_notice
> > > 老哥 这个配置文件我是这么配置的，但是后台地址打不开怎么处理（已经放行了端口号）
> > 
> > 
> > 你创建一个名字叫 test_class_notice 的数据库就能运行了
> 
> 是这样创建吗？
> ![image](https://user-images.githubusercontent.com/73337768/130906673-aab5f23e-6ce9-4b9f-a220-4ccb88cdea60.png)

用户名和密码填你数据库的,然后数据库名就是这个
